# Generated by Django 4.2 on 2025-09-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
