# Generated by Django 4.2 on 2025-09-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_image_alter_subcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
