"""
Django settings for carpal project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Base directory for logs
LOG_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=lambda v: [s.strip() for s in v.split(',')])

# Optional public storefront URL used in product links returned to the chatbot.
# Example: https://shop.example.com/products/{product_id}
# When it is not configured, the chatbot falls back to the public product API URL.
PRODUCT_PAGE_URL_TEMPLATE = config('PRODUCT_PAGE_URL_TEMPLATE', default='')

# Shared secret for server-to-server access to /api/chatbot/products/*.
# An empty value deliberately rejects every chatbot API request.
CHATBOT_API_KEY = config('CHATBOT_API_KEY', default='')


# Application definition

INSTALLED_APPS = [
    # ! CUSTOMIZE ADMIN PANEL
    'jazzmin',

    # ! FOR ADMIN PANEL DATE RANGE FILTER
    'rangefilter',

    # ! DEFAULT APPS
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.sites',

    # ! CORS POLICY
    'corsheaders',

    # ! REST FRAMEWORK 
    'rest_framework',

    # ! FOR CELERY TASKS
    'django_celery_beat',
    'django_celery_results',
    
    # ? For JWT Authentication
    'rest_framework.authtoken',
    'django_rest_passwordreset',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    
    # ? For Social Login
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # ! Created Folders
    'analytics.apps.AnalyticsConfig',
    'app.apps.AppConfig',
    'cart.apps.CartConfig',
    'coupon.apps.CouponConfig',
    'driver.apps.DriverConfig',
    'mechanic.apps.MechanicConfig',
    'notification.apps.NotificationConfig',
    'order.apps.OrderConfig',
    'payment.apps.PaymentConfig',
    'product.apps.ProductConfig',
    'review.apps.ReviewConfig',
    'shipping.apps.ShippingConfig',
    'vendor.apps.VendorConfig',
    'wishlist.apps.WishlistConfig',
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',                          # ? Middleware for serving static files
    "django.contrib.sessions.middleware.SessionMiddleware",
    'corsheaders.middleware.CorsMiddleware',                               # ? Middleware for CORS Policy
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "carpal.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "carpal.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }


# ! FOR PRODUCTION
DATABASES = {
    'default': {
        'ENGINE': config('DATABASE_ENGINE', default='django.db.backends.sqlite3'),
        'NAME': config('DATABASE_NAME', default='db.sqlite3'),
        'USER': config('DATABASE_USER', default=''),
        'PASSWORD': config('DATABASE_PASSWORD', default=''),
        'HOST': config('DATABASE_HOST', default=''),
        'PORT': config('DATABASE_PORT', default='5432'),
        'OPTIONS': {
            'sslmode': config('DATABASE_SSLMODE', default='prefer'),
        },
    }
}


# Coolify terminates HTTPS at its reverse proxy and forwards this header.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='',
    cast=lambda v: [origin.strip() for origin in v.split(',') if origin.strip()],
)


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'staticfiles'),] # For Development
STATIC_ROOT = os.path.join(BASE_DIR, 'static') # For Deployment

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ! Added This Parts
# ? SETTINGS FOR REST FRAMEWORK
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        # 'rest_framework.renderers.BrowsableAPIRenderer',  # ? This will hide the browser view of the API
    ],
}


# ? AUTH Token validity timming
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=180), # 6 months
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365), # 1 year
    'ROTATE_REFRESH_TOKENS': True,
}


# ? https://stackoverflow.com/questions/25468676/django-sites-model-what-is-and-why-is-site-id-1
SITE_ID = 1


# ? User Model Changes Abstract User
AUTH_USER_MODEL = 'app.User'


AUTHENTICATION_BACKENDS = [
    'allauth.account.auth_backends.AuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# ? Email Settings
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)


# ? CORS POLICY SETTINGS
CORS_ORIGIN_WHITELIST = config(
    'CORS_ORIGIN_WHITELIST',
    default='',
    cast=lambda v: [origin.strip() for origin in v.split(',') if origin.strip()],
)


CORS_ALLOW_METHODS = [ 'DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT', ]

CORS_ALLOW_HEADERS = [ 'accept', 'accept-encoding', 'authorization', 'content-type', 'content-disposition',
                        'dnt', 'origin', 'user-agent', 'x-csrftoken', 'x-requested-with',]



# ? Verify Uploaded File size (Middleware.py and Middleware in settings are also added)
# Add this to your file upload handlers
MAX_UPLOAD_SIZE = 10 * 1024 * 1024  # 10 MB

# ? This is the maximum size of a file that can be uploaded using the MemoryFileUploadHandler.
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600 # 100 MB

FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]


# ! SOCIAL LOGIN CREDENTIALS
# ? Google OAuth settings
GOOGLE_OAUTH2_CLIENT_ID = config('GOOGLE_OAUTH2_CLIENT_ID')
GOOGLE_OAUTH2_CLIENT_SECRET = config('GOOGLE_OAUTH2_CLIENT_SECRET')
GOOGLE_OAUTH2_REDIRECT_URI = config('GOOGLE_OAUTH2_REDIRECT_URI')


# ? Add RAZORPAY Credentials here
RAZORPAY_KEY_ID = config('RAZORPAY_KEY_ID')
RAZORPAY_KEY_SECRET = config('RAZORPAY_KEY_SECRET')


# ! Need to make changes here >>
# ? DJANGO ADMIN PANEL CUSTOMIZATION
JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "MotoSpar",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "MotoSpar",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "MotoSpar",

    # Logo to use for your site, must be present in static files, used for brand on top left
    # "site_logo": "",  # TODO: Add Image here if provided

    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    # "login_logo": "", # TODO: Add Image here if provided

    # Logo to use for login form in dark themes (defaults to login_logo)
    # "login_logo_dark": "", # TODO: Add Image here if provided

    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-circle",

    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    # "site_icon": "", # TODO: Add Image here if provided

    # Welcome text on the login screen
    "welcome_sign": "Welcome to MotoSpar",

    # Copyright on the footer
    "copyright": "MotoSpar",

    # List of model admins to search from the search bar, search bar omitted if excluded
    # If you want to use a single search field you dont need to use a list, you can use a simple string 
    # "search_model": ["auth.User", "auth.Group"],

    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
    # "user_avatar": "", # TODO: Add Image here if provided

    ############
    # Top Menu #
    ############

    # Links to put along the top menu
    # "topmenu_links": [

    #     # Url that gets reversed (Permissions can be added)
    #     {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},

    #     # external url that opens in a new window (Permissions can be added)
    #     {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},

    #     # model admin to link to (Permissions checked against model)
    #     {"model": "auth.User"},

    #     # App with dropdown menu to all its models pages (Permissions checked against models)
    #     {"app": "books"},
    # ],

    #############
    # User Menu #
    #############

    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    # "usermenu_links": [
    #     {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
    #     {"model": "auth.user"}
    # ],

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": True,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": [],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [],

    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    # "order_with_respect_to": ["auth", "books", "books.author", "books.book"],

    # Custom links to append to app groups, keyed on app name
    # "custom_links": {
    #     "books": [{
    #         "name": "Make Messages", 
    #         "url": "make_messages", 
    #         "icon": "fas fa-comments",
    #         "permissions": ["books.view_book"]
    #     }]
    # },

    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2,5.7.1,5.7.0,5.6.3,5.5.0,5.4.2
    # for the full list of 5.13.0 free icon classes
    "icons": {
        # Auth icons...
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",

        # Social account icons...
        "socialaccount.SocialAccount": "fas fa-user",  # Custom icon for SocialAccount
        "socialaccount.SocialApp": "fas fa-cogs",  # Custom icon for SocialApplication
        "socialaccount.SocialToken": "fas fa-key",  # Custom icon for SocialToken

        # Other icons...
        "account.EmailAddress": "far fa-envelope",  # Custom icon for EmailAddress
        "authtoken.Token": "fas fa-key",  # Custom icon for Token
        "django_rest_passwordreset.ResetPasswordToken": "fas fa-key",  # Custom icon for ResetPasswordToken
        "sites.Site": "fas fa-globe",  # Custom icon for Site
        "token_blacklist.OutstandingToken": "fas fa-list",  # Custom icon for OutstandingToken
        "token_blacklist.BlacklistedToken": "fas fa-ban",   # Custom icon for BlacklistedToken

        # Celery-related icons
        "django_celery_beat.PeriodicTask": "fas fa-clock",  # Periodic Task: Clock icon
        "django_celery_beat.IntervalSchedule": "fas fa-history",  # Interval Schedule: History icon
        "django_celery_beat.CrontabSchedule": "fas fa-calendar-alt",  # Crontab Schedule: Calendar icon
        "django_celery_beat.SolarSchedule": "fas fa-sun",  # Solar Schedule: Sun icon
        "django_celery_beat.ClockedSchedule": "fas fa-stopwatch",  # Clocked Schedule: Stopwatch icon
        "django_celery_results.TaskResult": "fas fa-tasks",  # Task Result: Tasks icon
        "django_celery_results.GroupResult": "fas fa-layer-group",  # Group Result: Layer group icon

        # Analytics icons...

        # App icons...
        "app.User": "fas fa-user",
        "app.PasswordResetOTP": "fas fa-key",  # A key icon for PasswordResetOTP
        "app.ContactUs": "fas fa-envelope",  # Chosen icon for ContactUs
        
        # Cart icons...
        "cart.Cart": "fas fa-shopping-cart",  # A shopping cart icon for carts
        "cart.CartItem": "fas fa-cart-plus",  # A plus in cart icon for cart items

        # Coupon icons...
        
        # Driver icons...
        "driver.Driver": "fas fa-car",  # A car icon to represent drivers
        
        # Mechanic icons...
        "mechanic.MechanicProfile": "fas fa-wrench",  # A wrench icon for mechanic profiles
        "mechanic.MechanicJob": "fas fa-tools",  # A tools icon for mechanic jobs
        "mechanic.MechanicJobImage": "fas fa-image",  # An image icon for mechanic job images
        "mechanic.MechanicReportApp": "fas fa-file-alt",  # A file icon for mechanic reports
        "mechanic.MechanicPlatformFee": "fas fa-money-bill-wave",  # A money bill icon for mechanic platform fees
        
        # Notification icons...
        "notification.Notification": "fas fa-bell",  # A bell icon for notifications

        # Order icons...
        "order.Order": "fas fa-receipt",  # A receipt icon for orders
        "order.OrderItem": "fas fa-box-open",  # A box open icon for order items
        
        # Payment icons...

        # Product icons...
        "product.Category": "fas fa-tags",  # A tag icon for categories
        "product.SubCategory": "fas fa-tag",  # A tag icon for subcategories
        "product.Product": "fas fa-box",  # A box icon for products
        "product.ProductVariant": "fas fa-cubes",  # A cubes icon for product variants
        "product.ProductImage": "fas fa-image",  # An image icon for product images
        "product.ProductRequest": "fas fa-shopping-cart",  # A shopping cart icon for product requests
        "product.ProductRequestImage": "fas fa-file-image",  # A file image icon for product request images
        
        # Review icons...
        "review.Review": "fas fa-star",  # A star icon for product reviews
        "review.ReviewImage": "fas fa-camera",  # A camera icon for review images
        
        # Shipping icons...
        "shipping.ShippingAddress": "fas fa-truck",  # A truck icon for shipping addresses
        "shipping.BillingAddress": "fas fa-credit-card",  # A credit card icon for billing addresses

        # Vendor icons...
        "vendor.VendorProfile": "fas fa-store",  # A store icon for vendor profiles
        "vendor.VendorStock": "fas fa-boxes",  # A boxes icon for vendor stock

        # Wishlist icons...
        "wishlist.Wishlist": "fas fa-heart",  # A heart icon for wishlists
        "wishlist.WishlistItem": "fas fa-heart-broken",  # A broken heart icon for wishlist items

    },

    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,

    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": None,
    "custom_js": None,
    # Whether to link font from fonts.googleapis.com (use custom_css to supply font otherwise)
    "use_google_fonts_cdn": True,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": False, # ?: Make this TRUE if need to change the UI

    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    # "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    # Add a language dropdown into the admin
    # "language_chooser": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-orange",
    "accent": "accent-danger",
    "navbar": "navbar-orange navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-light-danger",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "minty",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success"
    }
}


# ? CELERY SETTINGS
CELERY_BROKER_URL = config('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND')

CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

CELERY_TIMEZONE = 'Asia/Kolkata'

CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # Hard time limit (30 mins)
CELERY_TASK_SOFT_TIME_LIMIT = None  # No soft time limit
CELERY_TASK_ACKS_LATE = True  # Avoid losing tasks if a worker crashes
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # Requeue task if worker dies
CELERY_TASK_IGNORE_RESULT = False  # Store task results
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

CELERY_TASK_RETRY_DELAY = 5  # Retry after 5 seconds
CELERY_TASK_MAX_RETRIES = 3  # Retry up to 3 times


# ? Logger Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'bulk_upload.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,  # Keep up to 5 backup files
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'bulk_upload': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
