# Generated by Django 4.2 on 2026-02-19 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True)),
                ('notification_type', models.CharField(choices=[('INFO', 'INFO'), ('PROMO', 'PROMO'), ('ORDER', 'ORDER'), ('PAYMENT', 'PAYMENT'), ('SHIPPING', 'SHIPPING'), ('GENERAL', 'GENERAL'), ('MECHANIC_JOB', 'MECHANIC_JOB')], default='GENERAL', max_length=20)),
                ('status', models.CharField(choices=[('UNREAD', 'UNREAD'), ('READ', 'READ')], default='UNREAD', max_length=10)),
                ('redirect_url', models.URLField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('is_urgent', models.BooleanField(default=False)),
                ('extra_data', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
