# Generated by Django 4.2 on 2026-02-19 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('driver', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_code', models.CharField(editable=False, max_length=20, null=True, unique=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('PAYMENT_GATEWAY', 'PAYMENT_GATEWAY'), ('CASH_ON_DELIVERY', 'CASH_ON_DELIVERY')], default='CASH_ON_DELIVERY', max_length=50)),
                ('payment_status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE')], default='PENDING', max_length=20)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('driver_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('driver_otp', models.CharField(blank=True, max_length=6)),
                ('provider_order_id', models.CharField(blank=True, max_length=64)),
                ('payment_id', models.CharField(blank=True, max_length=64)),
                ('signature_id', models.CharField(blank=True, max_length=128)),
                ('is_successful', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shipping.billingaddress')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to=settings.AUTH_USER_MODEL)),
                ('driver_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver_orders', to='driver.driver')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipping.shippingaddress')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.CharField(choices=[('PENDING', 'PENDING'), ('ADMIN_REVIEW', 'ADMIN_REVIEW'), ('ASSIGNED_TO_VENDOR', 'ASSIGNED_TO_VENDOR'), ('VENDOR_ACCEPTED', 'VENDOR_ACCEPTED'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=20)),
                ('item_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE')], default='PENDING', max_length=20)),
                ('mechanic_fees_for_customer', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mechanic_fees_for_mechanic', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mechanic_otp', models.CharField(blank=True, max_length=6)),
                ('installation_required', models.BooleanField(default=False)),
                ('vendor_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vendor_payment_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_orders', to=settings.AUTH_USER_MODEL)),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mechanic_orders', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='order.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.productvariant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'variant'), name='unique_variant_in_order'),
        ),
    ]
