# Generated by Django 4.2 on 2026-09-28 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_productimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="requires_fitment",
            field=models.BooleanField(
                default=False,
                help_text="Only recommend this product after confirming vehicle compatibility.",
            ),
        ),
        migrations.CreateModel(
            name="ProductCompatibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("year_from", models.IntegerField()),
                ("year_to", models.IntegerField()),
                (
                    "engine_variant",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatibilities",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "ordering": ["make", "model", "year_from", "year_to"],
            },
        ),
        migrations.AddIndex(
            model_name="productcompatibility",
            index=models.Index(
                fields=["make", "model"], name="product_comp_make_model_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productcompatibility",
            index=models.Index(fields=["product"], name="product_comp_product_idx"),
        ),
        migrations.AddConstraint(
            model_name="productcompatibility",
            constraint=models.CheckConstraint(
                check=models.Q(("year_to__gte", models.F("year_from"))),
                name="product_comp_valid_year_range",
            ),
        ),
    ]
