# Generated by Django 4.2 on 2026-02-19 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_accepted', models.BooleanField(default=False, help_text='Indicates if the mechanic has accepted the job')),
                ('job_status', models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failure', 'failure')], default='pending', max_length=20)),
                ('mechanic_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_date', models.DateTimeField(blank=True, help_text='Date and time when the job started', null=True)),
                ('completion_date', models.DateTimeField(blank=True, help_text='Date and time when the job was completed', null=True)),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='Scheduled date and time for the job', null=True)),
                ('payment_date', models.DateField(blank=True, help_text='Date when payment was processed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the job')),
                ('decline_reason', models.TextField(blank=True, help_text='Reason for declining the job', null=True)),
                ('review', models.TextField(blank=True, help_text='Review given by the customer')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Rating given by the customer (1.0-5.0)', max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('job_type', models.ForeignKey(blank=True, help_text='Type of mechanic job', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mechanic_jobs', to='product.jobtype')),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_mechanic_jobs', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mechanic_jobs', to='order.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='MechanicProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expertise', models.CharField(blank=True, max_length=255)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('base_address', models.TextField(blank=True)),
                ('base_city', models.CharField(blank=True, max_length=32)),
                ('base_state', models.CharField(blank=True, max_length=16)),
                ('base_country', models.CharField(blank=True, max_length=32)),
                ('base_postal_code', models.CharField(blank=True, max_length=8)),
                ('latitude', models.DecimalField(blank=True, decimal_places=20, max_digits=24, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=20, max_digits=24, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('working_hours', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('ifsc_code', models.CharField(blank=True, max_length=11)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('service_types', models.TextField(blank=True)),
                ('uploaded_documents', models.FileField(blank=True, null=True, upload_to='mechanic_documents/')),
                ('uploaded_documents_type', models.CharField(blank=True, help_text="Type of the uploaded document (e.g. 'License', 'Certification')", max_length=50, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('total_top_up', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount topped up by the mechanic', max_digits=10)),
                ('top_up_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current top-up balance available', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MechanicReportApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_type', models.CharField(choices=[('app_preference', 'app_preference'), ('report_issue', 'report_issue'), ('other', 'other')], help_text='Type of text content (e.g. issue, feedback, note)', max_length=50)),
                ('text_content', models.TextField(help_text='Text content related to the mechanic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='mechanic.mechanicprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MechanicPlatformFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fee_amount', models.DecimalField(decimal_places=2, help_text='Amount of platform fee charged', max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE')], default='PENDING', max_length=20)),
                ('provider_transaction_id', models.CharField(blank=True, help_text='Transaction ID from payment provider', max_length=64)),
                ('payment_id', models.CharField(blank=True, help_text='Payment ID for tracking', max_length=64)),
                ('signature_id', models.CharField(blank=True, help_text='Signature ID for payment verification', max_length=128)),
                ('is_successful', models.BooleanField(default=False, help_text='Indicates if the fee payment was successful')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_fees', to='mechanic.mechanicprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MechanicJobImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Image associated with the mechanic job', upload_to='mechanic_job_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the image was uploaded')),
                ('description', models.TextField(blank=True, help_text='Optional description of the image', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the image record was created')),
                ('last_modified_at', models.DateTimeField(auto_now=True, help_text='Date and time when the image record was last modified')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the image is active')),
                ('mechanic_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mechanic.mechanicjob')),
            ],
            options={
                'verbose_name': 'Mechanic Job Image',
                'verbose_name_plural': 'Mechanic Job Images',
            },
        ),
        migrations.AddConstraint(
            model_name='mechanicjob',
            constraint=models.UniqueConstraint(fields=('order_item',), name='unique_mechanic_job_per_order_item'),
        ),
    ]
