# Generated by Django 4.2 on 2026-02-19 06:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='driver_profiles/')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_type', models.CharField(blank=True, max_length=20)),
                ('license_expiry_date', models.DateField(blank=True)),
                ('license_status', models.CharField(choices=[('valid', 'Valid'), ('expired', 'Expired'), ('suspended', 'Suspended')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('employment_status', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contractor', 'Contractor')], default='full_time', max_length=50)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
