# Generated by Django 4.2 on 2026-02-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_for_me_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
